### ISSUE TITLE
Exception Error Opening Movie: Southpaw

### ISSUE THREAD

**Issue by Hiltronix** [phil65/script.extendedinfo#21]
Hello,

I get an exception error when opening a particular movie in the Upcoming Movies of ExtendedInfo Script 3.0.0.

When I select the movie named "Southpaw" from "Upcoming movies (Rotten Tomatoes)" I consistently get an exception error, that leaves the busydialog open, and requiring the user to close and reopen Kodi, due (i assume) to the busydialog not being closed on an exception error.

The exception from the error log is below.

12:03:35 T:6364   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Carey\AppData\Roaming\Kodi\addons\script.extendedinfo\plugin.py", line 91, in <module>
                                                Main()
                                              File "C:\Users\Carey\AppData\Roaming\Kodi\addons\script.extendedinfo\plugin.py", line 21, in __init__
                                                start_info_actions(self.infos, self.params)
                                              File "C:\Users\Carey\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 362, in start_info_actions
                                                name=params.get("name", ""))
                                              File "C:\Users\Carey\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 73, in open_movie_info
                                                name=name)
                                              File "C:\Users\Carey\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\TheMovieDB.py", line 648, in get_movie_tmdb_id
                                                return response["movie_results"][0]["id"]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by phil65** [comment]
already fixed in latest master.
