### ISSUE TITLE
empty response from get_JSON_response not handled

### ISSUE THREAD

**Issue by kb0n** [phil65/script.extendedinfo#24]
Hi,
I saw a few errors in my kodi log similar to this:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.TypeError'>
Error Contents: 'bool' object has no attribute '__getitem__'
Traceback (most recent call last):
    File "/home/osmc/.kodi/addons/script.extendedinfo/plugin.py", line 91, in <module>
        Main()
    File "/home/osmc/.kodi/addons/script.extendedinfo/plugin.py", line 21, in __init__
        start_info_actions(self.infos, self.params)
    File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/process.py", line 249, in start_info_actions
        orderby=params.get("orderby", "relevance"))
    File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/YouTube.py", line 137, in search_youtube
        videos = handle_youtube_videos(results["items"], extended=True)
TypeError: 'bool' object has no attribute '__getitem__'
-->End of Python script error report<--
```
I did some digging and as far as I can see, it's because the return value fom `get_JSON_response` is not always checked.
I would've provided a simple fix attempt, like
```python
def get_JSON_response(...)
    ...
    if not results:
        results = []
    return results
```
, but I saw you handled it in some cases (`LastFM.py`, `RottenTomatoes.py`,..). And I'm not that familiar with your script, so I thought I just report it and leave the fixing to you ;)

**Comment by phil65** [comment]
should be fixed with https://github.com/phil65/script.extendedinfo/commit/cd21804341aee0796869eecebd1967b5192705f1
