### ISSUE TITLE
Youtube error

### ISSUE THREAD

**Issue by ronajon** [phil65/script.extendedinfo#27]
from my log i got this error in the Youtube.py file

08:52:03  83.233124 T:1660294176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: int() argument must be a string or a number, not 'NoneType'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.extendedinfo/plugin.py", line 91, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/script.extendedinfo/plugin.py", line 21, in __init__
                                                start_info_actions(self.infos, self.params)
                                              File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/process.py", line 249, in start_info_actions
                                                orderby=params.get("orderby", "relevance"))
                                              File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/YouTube.py", line 137, in search_youtube
                                                videos = handle_youtube_videos(results["items"], extended=True)
                                              File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/YouTube.py", line 52, in handle_youtube_videos
                                                vote_count = float(int(ext_item['statistics'].get('likeCount')) + int(ext_item['statistics'].get('dislikeCount')))
                                            TypeError: int() argument must be a string or a number, not 'NoneType'
                                            -->End of Python script error report<--
08:52:03  83.420113 T:1706333216   ERROR: GetDirectory - Error getting plugin://script.extendedinfo/?info=youtubesearch&&id="Ice Age: Continental Drift" TV show

**Comment by edd--** [comment]
Same problem here, can anyone please check this error ?

**Comment by phil65** [comment]
Please try https://github.com/phil65/script.extendedinfo/commit/a9a2fbd218320475072ca3d324a292251dfe442a

**Comment by phil65** [comment]
no answer = fixed I guess. ;)

**Comment by ronajon** [comment]
i added the change, will try as soon as possible
thx

**Comment by edd--** [comment]
fixed ! Thanks a lot !
