### ISSUE TITLE
invalid literal for int()  "festivalsonly" in script extendedinfo

### ISSUE THREAD

**Issue by Angelinas1** [phil65/script.extendedinfo#34]
20:42:16 T:1928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.extendedinfo\default.py", line 45, in <module>
                                                Main()
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.extendedinfo\default.py", line 19, in __init__
                                                start_info_actions(self.infos, self.params)
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 242, in start_info_actions
                                                distance=params.get("distance", ""))
                                              File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\LastFM.py", line 226, in get_near_events
                                                params = {"festivalsonly": int(festivals_only),
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--

**Comment by phil65** [comment]
could you try this? https://github.com/phil65/script.extendedinfo/commit/ae1364bcd06247b54f739cd22647f044a8f2e8fd

**Comment by Angelinas1** [comment]
working tnx
