### ISSUE TITLE
Play button not working

### ISSUE THREAD

**Issue by milnash** [phil65/script.extendedinfo#65]
`15:17:09.190 T:6288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exit_script() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\dator\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\dialogs\DialogMovieInfo.py", line 99, in onClick
                                                ch.serve(control_id, self)
                                              File "C:\Users\dator\AppData\Roaming\Kodi\addons\script.module.kodi65\lib\kodi65\actionhandler.py", line 291, in serve
                                                return view_function(wnd, control_id)
                                              File "C:\Users\dator\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\dialogs\DialogMovieInfo.py", line 218, in play_resume_button
                                                self.exit_script()
                                            TypeError: exit_script() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--`

**Comment by milnash** [comment]
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exit_script() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\dator\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\dialogs\DialogMovieInfo.py", line 99, in onClick
                                                ch.serve(control_id, self)
                                              File "C:\Users\dator\AppData\Roaming\Kodi\addons\script.module.kodi65\lib\kodi65\actionhandler.py", line 291, in serve
                                                return view_function(wnd, control_id)
                                              File "C:\Users\dator\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\dialogs\DialogMovieInfo.py", line 218, in play_resume_button
                                                self.exit_script()
                                            TypeError: exit_script() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--

**Comment by Angelinas1** [comment]
try this 
https://github.com/phil65/script.extendedinfo/pull/66/commits/454bcb0518d981665193620cb748de8b14fb8ee8
