### ISSUE TITLE
Kodi Log Error

### ISSUE THREAD

**Issue by Coolzero82** [phil65/script.extendedinfo#79]
Hi, I use CoreElec 8.90.2 and have the following error in the log:

`05:33:13.544 T:3892310896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.extendedinfo/plugin.py", line 134, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/script.extendedinfo/plugin.py", line 31, in __init__
                                                listitems = process.start_info_actions(info, self.params)
                                              File "/storage/.kodi/addons/script.extendedinfo/resources/lib/process.py", line 55, in start_info_actions
                                                return tmdb.get_movies("now_playing")
                                              File "/storage/.kodi/addons/script.extendedinfo/resources/lib/TheMovieDB.py", line 1180, in get_movies
                                                return handle_movies(response["results"], False, None)
                                              File "/storage/.kodi/addons/script.extendedinfo/resources/lib/TheMovieDB.py", line 302, in handle_movies
                                                sortkey=sortkey)
                                              File "/storage/.kodi/addons/script.module.kodi65/lib/kodi65/localdb.py", line 316, in merge_with_local
                                                get_list(["originaltitle", "imdbnumber"]))
                                              File "/storage/.kodi/addons/script.module.kodi65/lib/kodi65/localdb.py", line 294, in get_compare_info
                                                dct["titles"] = json.loads(addon.get_global("%s_titles.JSON" % media_type))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
05:33:14.233 T:3892310896 WARNING: CPythonInvoker(18, /storage/.kodi/addons/script.extendedinfo/plugin.py): the python script "/storage/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
05:33:14.236 T:3934237552   ERROR: GetDirectory - Error getting plugin://script.extendedinfo/?info=incinemamovies`

What is the problem and especially the solution?
Thank you

**Comment by sim590** [comment]
@Coolzero82 :

1. Use `` ``` `` to surround your block of code, not `` ` `` so that it becomes clear block of text ...
2. You could may be enhance your description of the issue. You're just throwing the error without saying what is the effect of that error.
3. Change the title to something relevant ...

@phil65: I have this error too and it happens every second time I use the UP arrow on a movie actor icon to get his info. The result: the plugin is not usable afterwards. I have to restart Kodi to get the UP-arrow function again. However, it won't ever work more than one time per restart ... That's very unpractical.

[Here][log] is the complete log of Kodi starting up and going to some movie info and hitting the UP arrow twice. The second time, the plugin crashes.

[log]: https://github.com/phil65/script.extendedinfo/files/3235172/kodi_extendedinfo.log

**Comment by sim590** [comment]
I have just found the issue about what I described. However, this does not have to do with #79's original description. I will open another issue about this.
